on: pull_request
name: Pull Request
jobs:
  build:
    name: Compile, Test, and Package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Fetch dependencies
      run: bin/sbt update
    - name: Run tests
      run: bin/sbt clean compile test package
