on: push
name: Push
jobs:
  compile:
    name: Compile and Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: bin/sbt clean compile test package
    - name: Build a POM
      run: bin/sbt makePom
      if: startsWith(github.ref, 'refs/tags/')
    - name: Release
      uses: softprops/action-gh-release@v1
      # only on tagged pushes, so releases
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/scala-2.11/data-validator_2.11-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}